# Generated by Django 5.2 on 2025-05-05 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_record_recording_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('price', models.IntegerField()),
                ('active', models.BooleanField(default=True)),
                ('date_create', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='record',
            name='service',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='service_records', to='records.service'),
            preserve_default=False,
        ),
    ]
