# Generated by Django 5.2 on 2025-05-06 08:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0004_alter_record_options_alter_service_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='first_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=55),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='record',
            name='last_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=55),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='record',
            name='recording_date',
            field=models.DateTimeField(),
        ),
    ]
