# Generated by Django 5.2 on 2025-05-01 08:13

import services.services
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_car_brand_car_name_car_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=services.services.upload_photo_car),
        ),
    ]
