# Generated by Django 5.2 on 2025-05-01 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_car_image'),
        ('users', '0006_profile_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('P', 'pending'), ('A', 'approved'), ('R', 'rejected'), ('C', 'completed')], default='P', max_length=1)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('date_create', models.DateTimeField(auto_now_add=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_records', to='cars.car')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_records', to='users.profile')),
            ],
        ),
    ]
