# Generated by Django 5.2 on 2025-05-02 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_record'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Record',
        ),
    ]
