# Generated by Django 5.2 on 2025-05-06 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_delete_record'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'verbose_name': 'Машина', 'verbose_name_plural': 'Машины'},
        ),
    ]
