# Generated by Django 5.2 on 2025-05-06 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_customeruser_options_alter_profile_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeruser',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
    ]
