# Generated by Django 5.2 on 2025-05-07 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_remove_customeruser_username'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customeruser',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='phone',
        ),
        migrations.AddField(
            model_name='customeruser',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
